import subprocess
import os
import shutil
from pathlib import Path
from Bio import SeqIO
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

path_to_out = '../code_output/script_1/'  # path to directory with files, generated by this code
Path(path_to_out).mkdir(parents=True, exist_ok=True)
os.chdir(path_to_out)

mfold_path = shutil.which('mfold')
if mfold_path is None:
    raise RuntimeError("mFold not found. Please install it and ensure it's on your PATH environment variable.")

#######################################################################################################################
# FILTERING

# remove duplications (PUs with the same coordinates, but on different strings)
command = ['awk', '-F\t', '!seen[$4 FS $5]++', '../../data/chr_repranger.tsv']
with open('chr_repranger_dedoubled.tsv', 'w') as outfile:
    subprocess.run(command, stdout=outfile, check=True)
command = ['awk', '-F\t', '!seen[$4 FS $5]++', '../../data/pl_repranger.tsv']
with open('pl_repranger_dedoubled.tsv', 'w') as outfile:
    subprocess.run(command, stdout=outfile, check=True)


# filter nested PUs
def filter_nested_h(in_file, out_file):
    with open(in_file, 'r') as input, open(out_file, 'w') as output:
        output.write(input.readline())
        two_start = 0
        two_stop = 0
        two_name = ''
        prev_nested = False
        while True:
            line = input.readline()
            line_ = line.split('\t')
            if not line_[0]:
                break
            if not prev_nested:
                one_start = two_start
                one_stop = two_stop
                one_name = two_name
            two_start = int(line_[3])
            two_stop = int(line_[4])
            two_name = line_[0]
            if two_stop - (two_stop - two_start) / 2 == one_stop - (one_stop - one_start) / 2:
                print(f'{two_name} nested in {one_name}')
                prev_nested = True
            else:
                output.write(line)
                prev_nested = False


subprocess.run(
    "{ head -n1 chr_repranger_dedoubled.tsv; tail -n +2 chr_repranger_dedoubled.tsv | sort -t'\t' -k4,4n; } > chr_repranger_dedoubled_sorted.tsv",
    shell=True, check=True)
filter_nested_h('chr_repranger_dedoubled_sorted.tsv', 'chr_repranger_dedoubled_sorted_unnested.tsv')
subprocess.run(
    "{ head -n1 pl_repranger_dedoubled.tsv; tail -n +2 pl_repranger_dedoubled.tsv | sort -t'\t' -k4,4n; } > pl_repranger_dedoubled_sorted.tsv",
    shell=True, check=True)
filter_nested_h('pl_repranger_dedoubled_sorted.tsv', 'pl_repranger_dedoubled_sorted_unnested.tsv')


# extract fasta sequences from filtered tsv
def extract_fasta(input_tsv, output_fasta):
    with open(input_tsv, 'r') as tsv_file, open(output_fasta, 'w') as fasta_file:
        tsv_file.readline()
        while True:
            line = tsv_file.readline().split('\t')
            if not line or len(line) < 15:
                break
            fasta_file.write(f'>{line[0]}_{line[1]} ({line[3]}..{line[4]})\n')
            fasta_file.write(f'{line[-1]}')


extract_fasta('chr_repranger_dedoubled_sorted_unnested.tsv', 'chr_repranger.fasta')
extract_fasta('pl_repranger_dedoubled_sorted_unnested.tsv', 'pl_repranger.fasta')


# predict mRNA secondary structures of hairpins with mfold
def mfold_output_parsing(path_to_ct_file):
    with open(path_to_ct_file) as file:
        lines = file.readlines()
        dG = lines[0].split(' ')[3]
        pairs = []
        for i in range(1, len(lines)):
            line = lines[i].split()
            if line[4] != '0':
                pairs.append([int(line[0]), int(line[4])])
    del line
    del lines

    counting_stem = False
    stem_size = 0
    loop_size = 0
    bulges = ''
    for i in range(len(pairs)):
        # going upwards alongside the stem, searching the loop
        if not counting_stem:
            if i != len(pairs) - 1:  # not last pair
                if pairs[i + 1][0] - pairs[i][0] > 1:  # loop?
                    if pairs[i][0] == pairs[i + 1][1] and pairs[i][1] == pairs[i + 1][0]:  # yes, loop
                        loop_size = pairs[i][1] - pairs[i][0] - 1
                        stem_size = 1
                        counting_stem = True
            else:
                break
        else:
            # going downwards alongside the stem, counting the stem length, searching for bulges
            if i != len(pairs) - 1:  # still not last pair
                left_dist = pairs[i][1] - pairs[i + 1][1]
                right_dist = pairs[i + 1][0] - pairs[i][0]
                if right_dist > 1 or left_dist > 1:
                    if right_dist == left_dist:
                        bulges += '_c' + str(right_dist - 1)
                    elif right_dist > 1:
                        bulges += '_r' + str(right_dist - 1)
                    else:
                        bulges += '_l' + str(left_dist - 1)
                stem_size += 1
            else:  # stem ended
                counting_stem = False

    return [stem_size, loop_size, dG, bulges]


def mfolding(mfold_output_dir, input_fasta, output_name):
    os.makedirs(f"./{mfold_output_dir}", exist_ok=True)
    with open(output_name, 'w') as output_file:
        output_file.write('name\tmolecule\tstart\tstop\tGC\tdG\tstem_len\tloop_size\tbulges\n')
        for record in SeqIO.parse(input_fasta, "fasta"):
            dir_name = f"./{mfold_output_dir}/{record.name}"
            os.makedirs(dir_name, exist_ok=True)
            with open(f'{dir_name}/{record.name}.fasta', 'w') as f:
                des_line = record.description.split(' ')
                h_name = des_line[0].split('_')[0]
                molecule = '_'.join(des_line[0].split('_')[1:3])
                coords = des_line[2].split('..')
                start = coords[0][1:]
                stop = coords[1][:-1]
                gc_content = round(((record.seq.count('G') + record.seq.count('C')) / len(record.seq)) * 100, 1)
                f.write('>' + str(record.name) + '\n')
                f.write(str(record.seq))
            print('\n\n\n')
            print(f'mfold on {record.name}')
            print('\n')
            subprocess.run([mfold_path, 'SEQ=' + f'{record.name}.fasta'], cwd=dir_name + '/')
            stem_size, loop_size, dG, bulges = mfold_output_parsing(f'{dir_name}/{record.name}_1.ct')
            output_file.write('\t'.join(
                [h_name, molecule, start, stop, str(gc_content), dG, str(stem_size), str(loop_size), bulges, '\n']))
            shutil.move(f'{dir_name}/{record.name}_1.ps', f'./{mfold_output_dir}/{record.name}_1.ps')
            shutil.rmtree(dir_name)


mfolding('chr_mfold', 'chr_repranger.fasta', 'chr_mfold.tsv')
mfolding('pl_mfold', 'pl_repranger.fasta', 'pl_mfold.tsv')

# filter PUs with bulges
command = "awk -F'\t' -v OFS='\t' 'NR==1 || !($9 ~ /[rl]/)' chr_mfold.tsv > chr_mfold_straight.tsv"
subprocess.run(command, shell=True, check=True)
command = "awk -F'\t' -v OFS='\t' 'NR==1 || !($9 ~ /[rl]/)' pl_mfold.tsv > pl_mfold_straight.tsv"
subprocess.run(command, shell=True, check=True)

# merge result files
command = "{ cat chr_mfold_straight.tsv; tail -n +2 pl_mfold_straight.tsv; } > all_mfold_straight.tsv"
subprocess.run(command, shell=True, check=True)

#######################################################################################################################
# VISUALIZATION (Fig. 2, 3)

# Fig 2.A,C,D

struc_df = pd.read_csv('all_mfold_straight.tsv', sep='\t', index_col=False)
p = sns.jointplot(data=struc_df, y="stem_len", x="dG", height=5, ratio=2,
                  marginal_ticks=True, kind="reg",
                  marginal_kws=dict(bins=28, fill=True))

p.ax_joint.tick_params(labelsize=12)
p.ax_marg_x.tick_params(labelsize=12)
p.ax_marg_y.tick_params(labelsize=12)

p.ax_joint.set_ylabel('Stem length, bp', fontsize=16)
p.ax_joint.set_xlabel('ΔG of structure, kcal/mol', fontsize=16)

plt.savefig('Fig_2.png')
plt.show()


# Fig 3

def plot_h_pos(h_positions, genome_length, tick_length=0.03, linewid=0.1, tick_interval_kb=100):
    angles = [pos / genome_length * 2 * np.pi for pos in h_positions]
    fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
    theta = np.linspace(0, 2 * np.pi, 1000)
    ax.plot(theta, [1] * 1000, color='black', linewidth=2)

    # Calculate tick positions
    genome_kb = genome_length / 1000
    tick_positions_kb = np.arange(0, genome_kb + tick_interval_kb / 2, tick_interval_kb)
    tick_positions_bp = tick_positions_kb * 1000
    tick_angles = [pos / genome_length * 2 * np.pi for pos in tick_positions_bp]

    valid_ticks = [(angle, kb) for angle, kb in zip(tick_angles, tick_positions_kb)
                   if kb * 1000 <= genome_length]

    for angle, kb in valid_ticks:
        ax.plot([angle, angle], [1, 1.05], color='black', linewidth=1)
        rotation_deg = -np.rad2deg(angle)
        rotation = rotation_deg + 90
        rotation = rotation % 360
        if 90 < rotation < 270:
            rotation += 180
        label = f'{kb:.0f}'
        ax.text(angle, 1.125, label,
                ha='center', va='center',
                rotation=rotation,
                rotation_mode='anchor',
                fontsize=12)

    # Draw h positions
    for angle in angles:
        ax.plot([angle, angle], [1 - tick_length, 1 + tick_length / 2],
                color='red', linewidth=linewid, solid_capstyle='round', alpha=0.8)

    ax.set_ylim(0.5, 1.3)
    ax.set_yticks([])
    ax.set_xticks([])
    ax.spines['polar'].set_visible(False)
    ax.grid(False)

    ax.set_theta_zero_location('N')
    ax.set_theta_direction(-1)

    plt.tight_layout()
    return fig, ax


def prepartion_for_plot(gff, mfold_file, in_linewid, in_tick_interval_kb, fig_name):
    with open(gff, 'r') as gff_file:
        while True:
            gff_line = gff_file.readline()
            if '##sequence-region' in gff_line:
                genome_length = int(gff_line.split(' ')[-1])
                break
    h_coords = []
    with open(mfold_file, 'r') as in_file:
        in_file.readline()
        while True:
            line = in_file.readline().strip().split('\t')
            if not line[0]:
                break
            h_coords.append(round(((int(line[2]) + int(line[3])) / 2)))

    fig, ax = plot_h_pos(
        h_positions=h_coords,
        genome_length=genome_length,
        tick_length=0.05,
        linewid=in_linewid,
        tick_interval_kb=in_tick_interval_kb)
    plt.savefig(fig_name)
    plt.show()


prepartion_for_plot('../../data/chr.gff3', 'chr_mfold_straight.tsv', 0.1, 200, 'Fig_3chr.png')
prepartion_for_plot('../../data/pl.gff3', 'pl_mfold_straight.tsv', 0.7, 10, 'Fig_3pl.png')
