import os
from pathlib import Path
import shutil
import subprocess
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

path_to_out = '../code_output/script_2/'  # path to directory with files, generated by this code
Path(path_to_out).mkdir(parents=True, exist_ok=True)
os.chdir(path_to_out)

# check if the necessary files already exist in code_output/script_1/ directory. If False, use pre-computed files
chr_file_path = Path('../script_1/chr_mfold_straight.tsv')
pl_file_path = Path('../script_1/pl_mfold_straight.tsv')

if chr_file_path.is_file() and pl_file_path.is_file():
    print('Using output files generated by the 1st script')
    path_to_in = '../script_1/'
else:
    print('Using pre-computed files')
    path_to_in = '../../intermediates/'

bedtools_path = shutil.which('bedtools')
if bedtools_path is None:
    raise RuntimeError("bedtools not found. Please install it and ensure it's on your PATH.")

########################################################################################################################
# COUNTING DISTANCES BETWEEN HAIRPINS AND CDSs

# extract hairpin coordinates
awk = 'BEGIN{OFS="\\t"} NR>1{print $2, $3, $4, $1, ".", "."}'
chr_cmd = f"awk -F'\\t' '{awk}' {path_to_in}chr_mfold_straight.tsv > chr_h.bed"
pl_cmd = f"awk -F'\\t' '{awk}' {path_to_in}pl_mfold_straight.tsv > pl_h.bed"
subprocess.run(chr_cmd, shell=True, check=True)
subprocess.run(pl_cmd, shell=True, check=True)

# filter chromosome and plasmid gff3 files for CDSs only
subprocess.run("""awk -F'\t' 'NR<=5 || $3=="CDS"' ../../data/chr.gff3 > chr_CDS.gff3""", shell=True, check=True)
subprocess.run("""awk -F'\t' 'NR<=5 || $3=="CDS"' ../../data/pl.gff3 > pl_CDS.gff3""", shell=True, check=True)

# sort by CDS first coordinate
subprocess.run("{ head -n5 chr_CDS.gff3; tail -n +6 chr_CDS.gff3 | sort -t'\t' -k4,4n; } > chr_CDS_sorted.gff3",
               shell=True, check=True)
subprocess.run("{ head -n5 pl_CDS.gff3; tail -n +6 pl_CDS.gff3 | sort -t'\t' -k4,4n; } > pl_CDS_sorted.gff3",
               shell=True, check=True)


# find CDSs around haipins with bedtools
# (dics for manual correction of cases when both closest CDSs are from the same side)
def find_CDSs_around(genome_gff, h_bed, human_dic, output_name):
    with open(output_name, 'w') as out_file:
        out_file.write('\t'.join(
            ['mol', 'h_start', 'h_stop', 'h_name', 'up_gene_ID', 'up_prot_ID', 'up_direct', 'up_start', 'up_stop',
             'up_prod', 'up_dist', 'down_gene_ID', 'down_prot_ID', 'down_direct', 'down_start', 'down_stop',
             'down_prod', 'down_dist', '\n']))
        command = [bedtools_path, 'closest', '-d', '-D', 'ref', '-k', '2', '-t', 'first', '-a',
                   h_bed, '-b', genome_gff]
        with open('bedtools_output.tsv', "w") as bedtools_output:
            subprocess.run(command, stdout=bedtools_output, check=True)
        with open('bedtools_output.tsv', "r") as bed_output:
            content = bed_output.readlines()
            it = iter(content)
            for _ in range(len(content) // 2):
                one_gene = next(it).strip().split('\t')
                two_gene = next(it).strip().split('\t')
                output_line = one_gene[0:4]
                h_coords = one_gene[1:3]
                closest_coords = one_gene[9:11]
                closest_direct = one_gene[12]
                closest_dist = one_gene[-1]
                further_coords = two_gene[9:11]
                further_direct = two_gene[12]
                further_dist = two_gene[-1]

                # parse closest gene
                for t in one_gene[14].split(';'):
                    if 'ID=' in t:
                        closest_prot_ID = t.split('=')[1].split('-')[1]
                    if 'product=' in t:
                        closest_product = t.split('=')[1]
                    if 'Parent=' in t:
                        closest_gene_ID = t.split('=')[1].split('-')[1]

                # ask for second closest gene if bedtools's variant is behind the closest one
                if int(closest_coords[0]) < int(further_coords[0]):  # closest CDS is upstream
                    up_coords = closest_coords[:]
                    dw_coords = further_coords[:]
                else:  # closest CDS is downstream
                    up_coords = further_coords[:]
                    dw_coords = closest_coords[:]

                if not (int(h_coords[0]) > int(up_coords[0]) and int(h_coords[1]) < int(
                        dw_coords[1])):  # hairpin not between two genes!!
                    if one_gene[3] in human_dic.keys():
                        correct_further_gene_ID = human_dic[one_gene[3]]
                    else:
                        correct_further_gene_ID = input(
                            f'Correct second gene for hairpin {one_gene[3]} closest to {closest_gene_ID} - ')
                    with open(genome_gff, 'r') as gff:
                        while True:
                            gff_line = gff.readline().strip()
                            if not gff_line:
                                raise ValueError(f"No {correct_further_gene_ID} in genome")
                            if correct_further_gene_ID in gff_line:
                                gff_line_ = gff_line.strip().split('\t')
                                further_coords = gff_line_[3:5]
                                further_direct = gff_line_[6]
                                further_gene_ID = correct_further_gene_ID
                                if closest_coords[0] < further_coords[0]:
                                    further_dist = str(int(further_coords[0]) - int(h_coords[1]))
                                else:
                                    further_dist = str(int(h_coords[0]) - int(further_coords[1]))
                                for t in gff_line_[8].split(';'):
                                    if 'ID=' in t:
                                        further_prot_ID = t.split('=')[1].split('-')[1]
                                    if 'product=' in t:
                                        further_product = t.split('=')[1]
                                break
                else:  # second CDS is correct

                    for t in two_gene[14].split(';'):
                        if 'ID' in t:
                            further_prot_ID = t.split('=')[1].split('-')[1]
                        if 'product' in t:
                            further_product = t.split('=')[1]
                        if 'Parent' in t:
                            further_gene_ID = t.split('=')[1].split('-')[1]

                if int(closest_coords[0]) < int(further_coords[0]):  # closest CDS is upstream
                    output_line.extend([closest_gene_ID, closest_prot_ID, closest_direct]
                                       + closest_coords + [closest_product, closest_dist])
                    output_line.extend([further_gene_ID, further_prot_ID, further_direct]
                                       + further_coords + [further_product, further_dist])
                else:  # closest CDS is downstream
                    output_line.extend([further_gene_ID, further_prot_ID, further_direct]
                                       + further_coords + [further_product, further_dist])
                    output_line.extend([closest_gene_ID, closest_prot_ID, closest_direct]
                                       + closest_coords + [closest_product, closest_dist])

                out_file.write('\t'.join(output_line) + '\n')


pl_dic = {'REP4a': 'ISO16_RS27860', 'REP68a': 'ISO16_RS28000', 'REP16d': 'ISO16_RS28035', 'REP64b': 'ISO16_RS28095',
          'REP35a': 'ISO16_RS28340',
          'REP35b': 'ISO16_RS28340', 'REP35c': 'ISO16_RS28340', 'REP35d': 'ISO16_RS28340', 'REP54a': 'ISO16_RS28375',
          'REP47d': 'ISO16_RS28525'}
chr_dic = {'REP2825d': 'ISO16_RS27760', 'REP2825c': 'ISO16_RS27760', 'REP2825b': 'ISO16_RS27760',
           'REP2825a': 'ISO16_RS27760', 'REP2780a': 'ISO16_RS00950', 'REP82d': 'ISO16_RS01375',
           'REP133a': 'ISO16_RS02175', 'REP133b': 'ISO16_RS02175', 'REP133c': 'ISO16_RS02175',
           'REP188a': 'ISO16_RS03215', 'REP188b': 'ISO16_RS03215', 'REP212a': 'ISO16_RS03655',
           'REP212b': 'ISO16_RS03655', 'REP212c': 'ISO16_RS03655', 'REP212d': 'ISO16_RS03655',
           'REP2653d': 'ISO16_RS03935', 'REP2653c': 'ISO16_RS03935', 'REP2653b': 'ISO16_RS03935',
           'REP2653a': 'ISO16_RS03935', 'REP2606a': 'ISO16_RS04835', 'REP259c': 'ISO16_RS04915',
           'REP259d': 'ISO16_RS04915', 'REP2578a': 'ISO16_RS05275', 'REP2556d': 'ISO16_RS05670',
           'REP298d': 'ISO16_RS05670', 'REP2556b': 'ISO16_RS05670', 'REP315a': 'ISO16_RS06050',
           'REP2514d': 'ISO16_RS06490', 'REP2511d': 'ISO16_RS06525', 'REP2511c': 'ISO16_RS06525',
           'REP2477c': 'ISO16_RS07120', 'REP2331a': 'ISO16_RS09600', 'REP2331b': 'ISO16_RS09600',
           'REP453a': 'ISO16_RS09660', 'REP482a': 'ISO16_RS10375', 'REP486a': 'ISO16_RS10415',
           'REP486b': 'ISO16_RS10415', 'REP486c': 'ISO16_RS10415', 'REP2255a': 'ISO16_RS11025',
           'REP2247b': 'ISO16_RS11175', 'REP2247a': 'ISO16_RS11175', 'REP519b': 'ISO16_RS11175',
           'REP522a': 'ISO16_RS11240', 'REP526a': 'ISO16_RS11420', 'REP526b': 'ISO16_RS11420',
           'REP526c': 'ISO16_RS11420', 'REP526d': 'ISO16_RS11420', 'REP2233a': 'ISO16_RS28680',
           'REP2231d': 'ISO16_RS29070', 'REP2231c': 'ISO16_RS29070', 'REP528': 'ISO16_RS11455',
           'REP2155a': 'ISO16_RS12780', 'REP633b': 'ISO16_RS13405', 'REP2109a': 'ISO16_RS13490',
           'REP643': 'ISO16_RS13605', 'REP687a': 'ISO16_RS28935', 'REP687c': 'ISO16_RS14540',
           'REP687d': 'ISO16_RS14540', 'REP1970b': 'ISO16_RS16265', 'REP1970a': 'ISO16_RS16265',
           'REP1962c': 'ISO16_RS16525', 'REP780a': 'ISO16_RS16525', 'REP782b': 'ISO16_RS16605',
           'REP1891a': 'ISO16_RS28950', 'REP846a': 'ISO16_RS17950', 'REP846b': 'ISO16_RS17950',
           'REP1877b': 'ISO16_RS18005', 'REP1840a': 'ISO16_RS18590', 'REP1818d': 'ISO16_RS19005',
           'REP1818c': 'ISO16_RS19005', 'REP926a': 'ISO16_RS19275', 'REP927c': 'ISO16_RS19285',
           'REP935a': 'ISO16_RS19345', 'REP935c': 'ISO16_RS19345', 'REP935b': 'ISO16_RS19345',
           'REP1798a': 'ISO16_RS19340', 'REP968a': 'ISO16_RS19955', 'REP1770b': 'ISO16_RS19955',
           'REP968b': 'ISO16_RS19955', 'REP1009a': 'ISO16_RS20645', 'REP1009b': 'ISO16_RS20645',
           'REP1009c': 'ISO16_RS20645', 'REP1009d': 'ISO16_RS20645', 'REP1064a': 'ISO16_RS21725',
           'REP1656a': 'ISO16_RS22305', 'REP1100b': 'ISO16_RS22375', 'REP1100c': 'ISO16_RS22375',
           'REP1635c': 'ISO16_RS22810', 'REP1210a': 'ISO16_RS24440', 'REP1210b': 'ISO16_RS24440',
           'REP1556c': 'ISO16_RS24665', 'REP1224c': 'ISO16_RS24665', 'REP1556b': 'ISO16_RS24665',
           'REP1533a': 'ISO16_RS25110', 'REP1264d': 'ISO16_RS25400', 'REP1438a': 'ISO16_RS26940'}

find_CDSs_around('pl_CDS_sorted.gff3', 'pl_h.bed', pl_dic, 'pl_CDS_around_h.tsv')
find_CDSs_around('chr_CDS_sorted.gff3', 'chr_h.bed', chr_dic, 'chr_CDS_around_h.tsv')


# correct distances between hairpins and closest CDSs found by bedtools
def correct_distances(output_name, cds_in_file, close_max_dist):
    with open(output_name, 'w') as out_file, open(cds_in_file, "r") as in_file:
        in_file.readline()
        out_file.write('\t'.join(
            ['mol', 'h_start', 'h_stop', 'h_name', 'up_gene_ID', 'up_prot_ID', 'up_direct', 'up_start', 'up_stop',
             'up_prod', 'up_dist', 'up_dist_type', 'down_gene_ID', 'down_prot_ID', 'down_direct', 'down_start',
             'down_stop', 'down_prod', 'down_dist', 'down_dist_type']) + '\n')
        while True:
            line = in_file.readline().split('\t')
            if not line[0]:
                break
            h_start = int(line[1])
            h_stop = int(line[2])
            # up_start = int(line[7])
            up_stop = int(line[8])
            dw_start = int(line[14])
            # dw_stop = int(line[15])

            up_type = ''
            up_dist = ''
            if h_start > up_stop:  # far or close
                up_dist = h_start - up_stop
                if up_dist < close_max_dist:
                    up_type = 'close'
                else:
                    up_type = 'far'
            elif h_start <= up_stop:  # overlap or inside
                if h_stop > up_stop:
                    up_type = 'overlap'
                    up_dist = h_start - up_stop
                else:
                    up_type = 'inside'

            dw_type = ''
            dw_dist = ''
            if dw_start > h_stop:  # far or close
                dw_dist = dw_start - h_stop - 1
                if dw_dist < close_max_dist:
                    dw_type = 'close'
                else:
                    dw_type = 'far'
            elif dw_start <= h_stop:  # overlap or inside
                if h_start < dw_start:
                    dw_type = 'overlap'
                    dw_dist = dw_start - h_stop - 1
                else:
                    dw_type = 'inside'

            line[10] = str(up_dist)
            line[17] = str(dw_dist)
            line.insert(11, up_type)
            line.append(dw_type)
            out_file.write('\t'.join(line) + '\n')


correct_distances('chr_CDS_around_h_cor_dist.tsv', 'chr_CDS_around_h.tsv', 100)
correct_distances('pl_CDS_around_h_cor_dist.tsv', 'pl_CDS_around_h.tsv', 100)

# merge result files
command = "{ cat chr_CDS_around_h_cor_dist.tsv; tail -n +2 pl_CDS_around_h_cor_dist.tsv; } > all_CDS_around_h_cor_dist.tsv"
subprocess.run(command, shell=True, check=True)

########################################################################################################################
# VISUALIZATION (Fig. 4)

# Fig. 4A

def prep_df_for_fig_4A(output_name, cds_in_file):
    with open(output_name, 'w') as out_file, open(cds_in_file, "r") as in_file:
        in_file.readline()
        out_file.write('\t'.join(
            ['mol', 'h_name', 'dist_type']) + '\n')
        while True:
            line = in_file.readline().strip().split('\t')
            if not line[0]:
                break
            out_line = []
            out_line.append(line[0])
            out_line.append(line[3])
            up_type = line[11]
            dw_type = line[19]

            if up_type == 'inside' or dw_type == 'inside':
                dist_type = 'inside'
            else:
                dist_type = 'outside'

            out_line.append(dist_type)
            out_file.write('\t'.join(out_line) + '\n')


prep_df_for_fig_4A('all_in_out_CDS_h_cor_dist.tsv', 'all_CDS_around_h_cor_dist.tsv')

struc_df = pd.read_csv(f'{path_to_in}all_mfold_straight.tsv', sep='\t', index_col=False)
dist_df = pd.read_csv('all_in_out_CDS_h_cor_dist.tsv', sep='\t', index_col=False)
plot_df = pd.DataFrame({f'{struc_df.columns[0]}': struc_df.iloc[:, 0], f'{struc_df.columns[6]}': struc_df.iloc[:, 6],
                        f'{dist_df.columns[2]}': dist_df.iloc[:, 2]})

bins = [2, 6, 10, 14, 18, 29]
labels = ['2-5', '6-9', '10-13', '14-17', '18-29']

plot_df['group'] = pd.cut(plot_df['stem_len'], bins=bins, labels=labels, right=False)
print(plot_df['group'].value_counts())
sns.set_style("whitegrid")

norm_cross_tab = pd.crosstab(plot_df['group'], plot_df['dist_type'], normalize='index')
ax = norm_cross_tab.plot(kind='bar', stacked=True, colormap='Wistia', figsize=(10, 6), edgecolor='black', linewidth=0.2)
plt.xlabel('Ranges of stem length, bp', fontsize=16)
plt.ylabel('Proportion (Normalized)', fontsize=16)
plt.legend(title='Position of PU relative to CDSs', bbox_to_anchor=(1.05, 1), loc='upper left', title_fontsize=14,
           fontsize=14)
plt.xticks(rotation=0, fontsize=12)
plt.yticks(fontsize=12)
plt.ylim(0, 1)
for container in ax.containers:
    ax.bar_label(container, fmt='%.2f', label_type='center', fontsize=12)
plt.tight_layout()
plt.savefig('Fig_4A')
plt.show()


# Fig. 4B

def prep_df_for_fig_4B(output_name, struc_file, cds_in_file):
    with open(output_name, 'w') as out_file, open(struc_file, "r") as in_struc_file, open(cds_in_file,
                                                                                          "r") as in_cds_file:
        in_struc_file.readline()
        in_cds_file.readline()
        out_file.write('\t'.join(
            ['h_name', 'stem_len', 'dist', '3_5_end']) + '\n')
        while True:
            line = in_cds_file.readline().strip().split('\t')
            if not line[0]:
                break
            stem_len = in_struc_file.readline().strip().split('\t')[6]
            if line[11] != 'inside' and line[19] != 'inside' and int(line[10]) < 3000 and int(line[18]) < 3000:
                out_line_start = [line[3], stem_len]

                up_dist = line[10]
                up_dir = line[6]
                up_out_line = []
                up_out_line.extend(out_line_start)
                up_out_line.append(up_dist)
                if up_dir == '+':
                    up_out_line.append("stop codon")
                else:
                    up_out_line.append("start codon")
                out_file.write('\t'.join(up_out_line) + '\n')

                dw_dist = line[18]
                dw_dir = line[14]
                dw_out_line = []
                dw_out_line.extend(out_line_start)
                dw_out_line.append(dw_dist)
                if dw_dir == '+':
                    dw_out_line.append("start codon")
                else:
                    dw_out_line.append("stop codon")
                out_file.write('\t'.join(dw_out_line) + '\n')


prep_df_for_fig_4B('dist_to_CDS_3_5.tsv', f'{path_to_in}all_mfold_straight.tsv', 'all_CDS_around_h_cor_dist.tsv')

graph_df = pd.read_csv('dist_to_CDS_3_5.tsv', sep='\t', index_col=False)
bins = [2, 6, 10, 14, 18, 29]
labels = ['2-5', '6-9', '10-13', '14-17', '18-29']
graph_df['group'] = pd.cut(graph_df['stem_len'], bins=bins, labels=labels, right=False)
print(pd.pivot_table(graph_df, values='dist', index='group', columns='3_5_end', aggfunc='count'))

g = sns.catplot(data=graph_df.sort_values("group"), x="group", y="dist", hue="3_5_end",
                kind="point")  # , legend=False, estimator=np.median, ci=None

plt.xlabel('Ranges of stem length, bp', fontsize=16)
plt.ylabel('Distance to nearest CDS, nt', fontsize=16)
g.legend.set_title('Which end of CDS is closer to PU')
g.legend.get_title().set_fontsize(14)
g.legend.set_bbox_to_anchor((1, 0.9))
plt.setp(g.legend.get_texts(), fontsize=14)
plt.grid(axis='y')
plt.xticks(rotation=0, fontsize=12)
plt.yticks(fontsize=12)
plt.savefig('Fig_4B')
plt.show()
