import os
from pathlib import Path
import subprocess
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

path_to_out = '../code_output/script_3/'  # path to directory with files, generated by this code
Path(path_to_out).mkdir(parents=True, exist_ok=True)
os.chdir(path_to_out)

# check if the necessary files already exist in code_output/script_1/ directory. If False, use pre-computed files
chr_1_file_path = Path('../script_1/chr_mfold_straight.tsv')
pl_1_file_path = Path('../script_1/pl_mfold_straight.tsv')
chr_2_file_path = Path('../script_2/chr_CDS_around_h_cor_dist.tsv')
pl_2_file_path = Path('../script_2/pl_CDS_around_h_cor_dist.tsv')

if chr_1_file_path.is_file() and pl_1_file_path.is_file() and chr_2_file_path.is_file() and pl_2_file_path.is_file():
    print('Using output files generated by the 1st and the 2nd scripts')
    path_to_in_1 = '../script_1/'
    path_to_in_2 = '../script_2/'
else:
    print('Using pre-computed files')
    path_to_in_1 = '../../intermediates/'
    path_to_in_2 = '../../intermediates/'

########################################################################################################################
# CLUSTERING HAIRPINS

def find_h_clusters(mfold_file, cds_file, out_file, dist_between):
    with open(mfold_file, 'r') as mfold_input, open(cds_file, 'r') as cds_input, open(out_file, 'w') as output:
        output.write('\t'.join(
            ['n_of_h', 'h_names', 'h_stem_lens', 'h_stem_len_av', 'dist_between_h', 'dist_between_h_av',
             'cluster_start', 'cluster_stop',
             'up_name', 'up_dist', 'up_utr', 'dw_name', 'dw_dist', 'dw_utr', 'av_dist', 'overlap', 'type']) + '\n')
        mfold_input.readline()
        cds_input.readline()
        two_name = ''
        two_start = 0
        two_stop = 0
        two_stem_len = 0
        inside_cluster = False
        h_cluster = {'h_names': [], 'h_stem_lens': [], 'h_stem_len_av': '', 'dist_between_h': [],
                     'dist_between_h_av': ''}
        type = ''
        while True:
            line = mfold_input.readline().split('\t')
            if not line[0]:
                break
            one_start = two_start
            one_stop = two_stop
            one_name = two_name
            one_stem_len = two_stem_len
            two_start = int(line[2])
            two_stop = int(line[3])
            two_name = line[0]
            two_stem_len = line[6]
            if two_start - one_stop < dist_between:
                if one_name not in h_cluster['h_names']:
                    inside_cluster = True
                    h_cluster['h_names'].append(one_name)
                    h_cluster['h_stem_lens'].append(one_stem_len)
                    cluster_start = one_start
                h_cluster['h_names'].append(two_name)
                h_cluster['h_stem_lens'].append(two_stem_len)
                h_cluster['dist_between_h'].append(str(two_start - one_stop - 1))
            else:
                if inside_cluster:
                    inside_cluster = False
                    cluster_end = one_stop
                    h_stem_lens = [int(x) for x in h_cluster['h_stem_lens']]
                    h_cluster['h_stem_len_av'] = str(sum(h_stem_lens) / len(h_stem_lens))
                    h_dists_between = [int(x) for x in h_cluster['dist_between_h']]
                    h_cluster['dist_between_h_av'] = str(sum(h_dists_between) / len(h_dists_between))
                    overlap = str(any(num < 0 for num in h_dists_between))

                    while True:
                        cds_line = cds_input.readline().split('\t')
                        if h_cluster['h_names'][0] == cds_line[3]:
                            first_h_up_type = cds_line[11]
                            first_h_dw_type = cds_line[19].strip()
                            up_name = cds_line[4]
                            up_dist = cds_line[10]
                            if cds_line[6] == '+':
                                up_utr = "'3"
                            else:
                                up_utr = "'5"
                        elif h_cluster['h_names'][-1] == cds_line[3]:
                            last_h_up_type = cds_line[11]
                            last_h_dw_type = cds_line[19].strip()
                            dw_name = cds_line[12]
                            dw_dist = cds_line[18]
                            if cds_line[14] == '+':
                                dw_utr = "'5"
                            else:
                                dw_utr = "'3"
                            break
                    av_dist = ''
                    if up_dist and dw_dist:
                        av_dist = str((int(up_dist) + int(dw_dist)) / 2)

                    if 'inside' in [first_h_up_type, first_h_dw_type] and 'inside' in [last_h_up_type, last_h_dw_type]:
                        type = 'inside'
                    else:
                        type = 'outside'

                    output.write('\t'.join(
                        [str(len(h_cluster['h_names'])), ';'.join(h_cluster['h_names']),
                         ';'.join(h_cluster['h_stem_lens']),
                         h_cluster['h_stem_len_av'], ';'.join(h_cluster['dist_between_h']),
                         h_cluster['dist_between_h_av'],
                         str(cluster_start), str(cluster_end),
                         up_name, up_dist, up_utr, dw_name, dw_dist, dw_utr, av_dist, overlap, type]) + '\n')
                    h_cluster = {'h_names': [], 'h_stem_lens': [], 'dist_between_h': []}


find_h_clusters(f'{path_to_in_1}chr_mfold_straight.tsv', f'{path_to_in_2}chr_CDS_around_h_cor_dist.tsv',
                'chr_h_clusters.tsv', 15)
find_h_clusters(f'{path_to_in_1}pl_mfold_straight.tsv', f'{path_to_in_2}pl_CDS_around_h_cor_dist.tsv',
                'pl_h_clusters.tsv', 15)

# merge result files
command = "{ cat chr_h_clusters.tsv; tail -n +2 pl_h_clusters.tsv; } > all_h_clusters.tsv"
subprocess.run(command, shell=True, check=True)

########################################################################################################################
# VISUALIZATION (Fig. 5)


# Fig. 5B

df = pd.read_csv('all_h_clusters.tsv', sep='\t', index_col=False)
dist_df = df['dist_between_h'].str.split(';').explode().astype(int).to_frame()

sns.histplot(dist_df, x='dist_between_h')
plt.xlabel('Distance between PUs in clusters, nt', fontsize=18)
plt.ylabel('Count', fontsize=18)
plt.xticks(rotation=0, fontsize=14)
plt.yticks(fontsize=14)
plt.savefig('Fig_5B')
plt.show()

# Fig. 5D

df = pd.read_csv('all_h_clusters.tsv', sep='\t', index_col=False)

overlap_values = sorted(df['overlap'].unique())
type_categories = sorted(df['type'].unique())
fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)
color_palette = sns.color_palette("colorblind", n_colors=len(type_categories))
for i, overlap_val in enumerate(overlap_values):
    subset = df[df['overlap'] == overlap_val]

    sns.countplot(
        data=subset,
        x='n_of_h',
        hue='type',
        dodge=0.2,
        ax=axes[i],
        palette=color_palette,
        order=sorted(df['n_of_h'].unique())  # Ensure consistent x-axis order
    )

    axes[i].tick_params(axis='both', labelsize=16)
    axes[i].set_title(f'Overlapping: {overlap_val}', fontsize=16)
    axes[i].set_xlabel('Number of PUs in a cluster', fontsize=16)

    if i == 0:
        axes[i].set_ylabel('Number of clusters', fontsize=16)
    else:
        axes[i].set_ylabel('')  # Remove y-label for second plot

    axes[i].legend_.remove()

    for container in axes[i].containers:
        axes[i].bar_label(container, fontsize=14)

plt.legend(title='Position relative to CDSs', bbox_to_anchor=(1.02, 1), loc='upper left', title_fontsize=16,
           fontsize=16)
plt.tight_layout()
plt.savefig('Fig_5D')
plt.show()

# Fig. 5E

df_ = pd.read_csv('all_h_clusters.tsv', sep='\t', index_col=False)
df = df_[df_['type'] != 'inside'].copy()

conditions = [
    (df['up_utr'] == "'3") & (df['dw_utr'] == "'3"),
    (df['up_utr'] == "'5") & (df['dw_utr'] == "'5"),
    ((df['up_utr'] == "'3") & (df['dw_utr'] == "'5")) | ((df['up_utr'] == "'5") & (df['dw_utr'] == "'3"))
]

choices = ['convergent', 'divergent', 'codirectional']

df['position'] = np.select(conditions, choices, default='other')
df.to_csv('cds_position.tsv', index=False)

df = pd.read_csv('cds_position.tsv', index_col=False)
sns.countplot(data=df, x='position')
plt.xlabel('Direction of CDSs around PU cluster', fontsize=18)
plt.ylabel('Count', fontsize=18)
plt.xticks(rotation=0, fontsize=14)
plt.yticks(fontsize=14)
plt.savefig('Fig_5E')
plt.show()
